"""phase4_extraction

Revision ID: 0004_phase4_extraction
Revises: 0003_phase3_retrieval
Create Date: 2026-07-23 23:32:08.608366
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004_phase4_extraction"
down_revision: str | None = "0003_phase3_retrieval"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ontology_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'retired')",
            name=op.f("ck_ontology_versions_valid_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ontology_versions")),
        sa.UniqueConstraint("code", "version", name="uq_ontology_versions_code_version"),
    )
    op.create_index(
        "uq_ontology_versions_one_active",
        "ontology_versions",
        ["code"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "prompt_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("task", sa.String(length=100), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("template_text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'retired')", name=op.f("ck_prompt_versions_valid_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_versions")),
        sa.UniqueConstraint("name", "version", name="uq_prompt_versions_name_version"),
    )
    op.create_table(
        "schema_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("schema_sha256", sa.String(length=64), nullable=False),
        sa.Column("schema_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schema_versions")),
        sa.UniqueConstraint("name", "version", name="uq_schema_versions_name_version"),
    )
    op.create_table(
        "entity_subtype_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ontology_version_id", sa.Uuid(), nullable=False),
        sa.Column("entity_type_code", sa.String(length=50), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ontology_version_id"],
            ["ontology_versions.id"],
            name=op.f("fk_entity_subtype_definitions_ontology_version_id_ontology_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_subtype_definitions")),
        sa.UniqueConstraint(
            "ontology_version_id",
            "entity_type_code",
            "code",
            name="uq_entity_subtype_definitions_version_type_code",
        ),
    )
    op.create_table(
        "entity_type_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ontology_version_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_fallback", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(
            ["ontology_version_id"],
            ["ontology_versions.id"],
            name=op.f("fk_entity_type_definitions_ontology_version_id_ontology_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_type_definitions")),
        sa.UniqueConstraint(
            "ontology_version_id", "code", name="uq_entity_type_definitions_version_code"
        ),
    )
    op.create_table(
        "extraction_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("vault_id", sa.Uuid(), nullable=False),
        sa.Column("model_profile_id", sa.Uuid(), nullable=False),
        sa.Column("prompt_version_id", sa.Uuid(), nullable=False),
        sa.Column("schema_version_id", sa.Uuid(), nullable=False),
        sa.Column("ontology_version_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("requested_chunk_count", sa.Integer(), nullable=False),
        sa.Column(
            "processed_chunk_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "valid_candidate_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "invalid_candidate_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("prompt_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "warnings_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'partial', 'failed')",
            name=op.f("ck_extraction_runs_valid_status"),
        ),
        sa.CheckConstraint(
            "requested_chunk_count > 0 AND processed_chunk_count >= 0",
            name=op.f("ck_extraction_runs_valid_counts"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_extraction_runs_job_id_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["model_profile_id"],
            ["model_profiles.id"],
            name=op.f("fk_extraction_runs_model_profile_id_model_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ontology_version_id"],
            ["ontology_versions.id"],
            name=op.f("fk_extraction_runs_ontology_version_id_ontology_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"],
            ["prompt_versions.id"],
            name=op.f("fk_extraction_runs_prompt_version_id_prompt_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["schema_version_id"],
            ["schema_versions.id"],
            name=op.f("fk_extraction_runs_schema_version_id_schema_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vault_id"],
            ["vaults.id"],
            name=op.f("fk_extraction_runs_vault_id_vaults"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extraction_runs")),
        sa.UniqueConstraint("job_id", name="uq_extraction_runs_job_id"),
    )
    op.create_index("ix_extraction_runs_created", "extraction_runs", ["created_at"], unique=False)
    op.create_table(
        "predicate_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ontology_version_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ontology_version_id"],
            ["ontology_versions.id"],
            name=op.f("fk_predicate_definitions_ontology_version_id_ontology_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_predicate_definitions")),
        sa.UniqueConstraint(
            "ontology_version_id", "code", name="uq_predicate_definitions_version_code"
        ),
    )
    op.create_table(
        "predicate_inverse_mappings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ontology_version_id", sa.Uuid(), nullable=False),
        sa.Column("predicate_code", sa.String(length=50), nullable=False),
        sa.Column("inverse_predicate_code", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["ontology_version_id"],
            ["ontology_versions.id"],
            name=op.f("fk_predicate_inverse_mappings_ontology_version_id_ontology_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_predicate_inverse_mappings")),
        sa.UniqueConstraint(
            "ontology_version_id",
            "predicate_code",
            name="uq_predicate_inverse_mappings_version_predicate",
        ),
    )
    op.create_table(
        "property_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ontology_version_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("value_type", sa.String(length=30), nullable=False),
        sa.Column(
            "allowed_values_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ontology_version_id"],
            ["ontology_versions.id"],
            name=op.f("fk_property_definitions_ontology_version_id_ontology_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_property_definitions")),
        sa.UniqueConstraint(
            "ontology_version_id", "code", name="uq_property_definitions_version_code"
        ),
    )
    op.create_table(
        "evidence_spans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("extraction_run_id", sa.Uuid(), nullable=False),
        sa.Column("document_version_id", sa.Uuid(), nullable=False),
        sa.Column("section_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("quote_text", sa.Text(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("quote_sha256", sa.String(length=64), nullable=False),
        sa.Column("chunk_content_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "validation_status",
            sa.String(length=20),
            server_default=sa.text("'exact'"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "validation_status = 'exact'", name=op.f("ck_evidence_spans_exact_only")
        ),
        sa.CheckConstraint(
            "char_start >= 0 AND char_end > char_start", name=op.f("ck_evidence_spans_valid_span")
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunks.id"],
            name=op.f("fk_evidence_spans_chunk_id_chunks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.id"],
            name=op.f("fk_evidence_spans_document_version_id_document_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["extraction_run_id"],
            ["extraction_runs.id"],
            name=op.f("fk_evidence_spans_extraction_run_id_extraction_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
            name=op.f("fk_evidence_spans_section_id_sections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_spans")),
    )
    op.create_index("ix_evidence_spans_chunk", "evidence_spans", ["chunk_id"], unique=False)
    op.create_table(
        "extraction_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("extraction_run_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("response_sha256", sa.String(length=64), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'succeeded', 'schema_invalid', 'provider_failed')",
            name=op.f("ck_extraction_chunks_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunks.id"],
            name=op.f("fk_extraction_chunks_chunk_id_chunks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["extraction_run_id"],
            ["extraction_runs.id"],
            name=op.f("fk_extraction_chunks_extraction_run_id_extraction_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extraction_chunks")),
        sa.UniqueConstraint("extraction_run_id", "chunk_id", name="uq_extraction_chunks_run_chunk"),
    )
    op.create_index(
        "ix_extraction_chunks_run_status",
        "extraction_chunks",
        ["extraction_run_id", "status"],
        unique=False,
    )
    op.create_table(
        "claim_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("extraction_run_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_span_id", sa.Uuid(), nullable=True),
        sa.Column("claim_text", sa.Text(), nullable=False),
        sa.Column("assertion_kind", sa.String(length=20), nullable=False),
        sa.Column(
            "review_status",
            sa.String(length=20),
            server_default=sa.text("'unreviewed'"),
            nullable=False,
        ),
        sa.Column("validation_status", sa.String(length=20), nullable=False),
        sa.Column(
            "validation_errors_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "validation_status IN ('valid', 'invalid')",
            name=op.f("ck_claim_candidates_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunks.id"],
            name=op.f("fk_claim_candidates_chunk_id_chunks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_span_id"],
            ["evidence_spans.id"],
            name=op.f("fk_claim_candidates_evidence_span_id_evidence_spans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["extraction_run_id"],
            ["extraction_runs.id"],
            name=op.f("fk_claim_candidates_extraction_run_id_extraction_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claim_candidates")),
    )
    op.create_table(
        "entity_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("extraction_run_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_span_id", sa.Uuid(), nullable=True),
        sa.Column("local_id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("entity_type_code", sa.String(length=50), nullable=False),
        sa.Column("entity_subtype_code", sa.String(length=100), nullable=True),
        sa.Column("proposed_subtype", sa.String(length=100), nullable=True),
        sa.Column("entity_scope", sa.String(length=30), nullable=False),
        sa.Column("assertion_kind", sa.String(length=20), nullable=False),
        sa.Column(
            "review_status",
            sa.String(length=20),
            server_default=sa.text("'unreviewed'"),
            nullable=False,
        ),
        sa.Column("validation_status", sa.String(length=20), nullable=False),
        sa.Column(
            "validation_errors_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "validation_status IN ('valid', 'invalid')",
            name=op.f("ck_entity_candidates_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunks.id"],
            name=op.f("fk_entity_candidates_chunk_id_chunks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_span_id"],
            ["evidence_spans.id"],
            name=op.f("fk_entity_candidates_evidence_span_id_evidence_spans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["extraction_run_id"],
            ["extraction_runs.id"],
            name=op.f("fk_entity_candidates_extraction_run_id_extraction_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_candidates")),
        sa.UniqueConstraint(
            "extraction_run_id", "chunk_id", "local_id", name="uq_entity_candidates_run_chunk_local"
        ),
    )
    op.create_table(
        "relationship_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("extraction_run_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_span_id", sa.Uuid(), nullable=True),
        sa.Column("subject_local_id", sa.String(length=20), nullable=False),
        sa.Column("predicate_code", sa.String(length=50), nullable=False),
        sa.Column("object_local_id", sa.String(length=20), nullable=False),
        sa.Column("assertion_kind", sa.String(length=20), nullable=False),
        sa.Column(
            "review_status",
            sa.String(length=20),
            server_default=sa.text("'unreviewed'"),
            nullable=False,
        ),
        sa.Column("network_layer", sa.String(length=30), nullable=True),
        sa.Column("validation_status", sa.String(length=20), nullable=False),
        sa.Column(
            "validation_errors_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "validation_status IN ('valid', 'invalid')",
            name=op.f("ck_relationship_candidates_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunks.id"],
            name=op.f("fk_relationship_candidates_chunk_id_chunks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_span_id"],
            ["evidence_spans.id"],
            name=op.f("fk_relationship_candidates_evidence_span_id_evidence_spans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["extraction_run_id"],
            ["extraction_runs.id"],
            name=op.f("fk_relationship_candidates_extraction_run_id_extraction_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relationship_candidates")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("relationship_candidates")
    op.drop_table("entity_candidates")
    op.drop_table("claim_candidates")
    op.drop_index("ix_extraction_chunks_run_status", table_name="extraction_chunks")
    op.drop_table("extraction_chunks")
    op.drop_index("ix_evidence_spans_chunk", table_name="evidence_spans")
    op.drop_table("evidence_spans")
    op.drop_table("property_definitions")
    op.drop_table("predicate_inverse_mappings")
    op.drop_table("predicate_definitions")
    op.drop_index("ix_extraction_runs_created", table_name="extraction_runs")
    op.drop_table("extraction_runs")
    op.drop_table("entity_type_definitions")
    op.drop_table("entity_subtype_definitions")
    op.drop_table("schema_versions")
    op.drop_table("prompt_versions")
    op.drop_index(
        "uq_ontology_versions_one_active",
        table_name="ontology_versions",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("ontology_versions")
    # ### end Alembic commands ###
