"""phase4_resolution_and_neo4j_projection

Revision ID: 0006_phase4_resolution_graph
Revises: 0005_phase4_registry_seed
Create Date: 2026-07-24 00:24:47.260502
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0006_phase4_resolution_graph"
down_revision: str | None = "0005_phase4_registry_seed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "identifier_normalization_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'retired')",
            name=op.f("ck_identifier_normalization_rules_valid_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identifier_normalization_rules")),
        sa.UniqueConstraint("code", "version", name="uq_identifier_rules_code_version"),
    )
    op.create_table(
        "neo4j_projection_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vault_id", sa.Uuid(), nullable=False),
        sa.Column("outbox_id", sa.Uuid(), nullable=True),
        sa.Column("snapshot_sha256", sa.String(length=64), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("object_count", sa.Integer(), nullable=False),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed')",
            name=op.f("ck_neo4j_projection_runs_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["outbox_id"],
            ["projection_outbox.id"],
            name=op.f("fk_neo4j_projection_runs_outbox_id_projection_outbox"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vault_id"],
            ["vaults.id"],
            name=op.f("fk_neo4j_projection_runs_vault_id_vaults"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_neo4j_projection_runs")),
        sa.UniqueConstraint(
            "vault_id", "snapshot_sha256", name="uq_neo4j_projection_runs_snapshot"
        ),
    )
    op.create_index(
        "ix_neo4j_projection_runs_vault_created",
        "neo4j_projection_runs",
        ["vault_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "claims",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("extraction_run_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_span_id", sa.Uuid(), nullable=False),
        sa.Column("claim_text", sa.Text(), nullable=False),
        sa.Column("assertion_kind", sa.String(length=20), nullable=False),
        sa.Column("review_status", sa.String(length=20), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f("ck_claims_valid_status")),
        sa.ForeignKeyConstraint(
            ["evidence_span_id"],
            ["evidence_spans.id"],
            name=op.f("fk_claims_evidence_span_id_evidence_spans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["extraction_run_id"],
            ["extraction_runs.id"],
            name=op.f("fk_claims_extraction_run_id_extraction_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_candidate_id"],
            ["claim_candidates.id"],
            name=op.f("fk_claims_source_candidate_id_claim_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claims")),
        sa.UniqueConstraint("source_candidate_id", name="uq_claims_candidate"),
    )
    op.create_index("ix_claims_run_status", "claims", ["extraction_run_id", "status"], unique=False)
    op.create_table(
        "entities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vault_id", sa.Uuid(), nullable=False),
        sa.Column("ontology_version_id", sa.Uuid(), nullable=False),
        sa.Column("created_from_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("entity_type_code", sa.String(length=50), nullable=False),
        sa.Column("entity_subtype_code", sa.String(length=100), nullable=True),
        sa.Column("entity_scope", sa.String(length=30), nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("merged_into_entity_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'merged', 'superseded')", name=op.f("ck_entities_valid_status")
        ),
        sa.ForeignKeyConstraint(
            ["created_from_candidate_id"],
            ["entity_candidates.id"],
            name=op.f("fk_entities_created_from_candidate_id_entity_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["merged_into_entity_id"],
            ["entities.id"],
            name=op.f("fk_entities_merged_into_entity_id_entities"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["ontology_version_id"],
            ["ontology_versions.id"],
            name=op.f("fk_entities_ontology_version_id_ontology_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vault_id"],
            ["vaults.id"],
            name=op.f("fk_entities_vault_id_vaults"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entities")),
        sa.UniqueConstraint(
            "created_from_candidate_id", name=op.f("uq_entities_created_from_candidate_id")
        ),
    )
    op.create_index(
        "ix_entities_scope_status", "entities", ["entity_scope", "status"], unique=False
    )
    op.create_index(
        "ix_entities_type_normalized",
        "entities",
        ["entity_type_code", "normalized_name"],
        unique=False,
    )
    op.create_table(
        "entity_aliases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("source_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_span_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column("normalized_alias", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=20), nullable=True),
        sa.Column(
            "validation_status",
            sa.String(length=20),
            server_default=sa.text("'exact'"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
            name=op.f("fk_entity_aliases_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_span_id"],
            ["evidence_spans.id"],
            name=op.f("fk_entity_aliases_evidence_span_id_evidence_spans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_candidate_id"],
            ["entity_candidates.id"],
            name=op.f("fk_entity_aliases_source_candidate_id_entity_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_aliases")),
        sa.UniqueConstraint("entity_id", "source_candidate_id", name="uq_entity_aliases_candidate"),
    )
    op.create_index(
        "ix_entity_aliases_normalized", "entity_aliases", ["normalized_alias"], unique=False
    )
    op.create_table(
        "entity_identifiers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("source_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_span_id", sa.Uuid(), nullable=False),
        sa.Column("normalization_rule_id", sa.Uuid(), nullable=False),
        sa.Column("identifier_kind", sa.String(length=40), nullable=False),
        sa.Column("identifier_value", sa.Text(), nullable=False),
        sa.Column("normalized_value", sa.Text(), nullable=False),
        sa.Column("entity_type_code", sa.String(length=50), nullable=False),
        sa.Column("entity_scope", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
            name=op.f("fk_entity_identifiers_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_span_id"],
            ["evidence_spans.id"],
            name=op.f("fk_entity_identifiers_evidence_span_id_evidence_spans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["normalization_rule_id"],
            ["identifier_normalization_rules.id"],
            name=op.f("fk_entity_identifiers_normalization_rule_id_identifier_normalization_rules"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_candidate_id"],
            ["entity_candidates.id"],
            name=op.f("fk_entity_identifiers_source_candidate_id_entity_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_identifiers")),
        sa.UniqueConstraint(
            "entity_id",
            "identifier_kind",
            "normalized_value",
            name="uq_entity_identifiers_entity_value",
        ),
        sa.UniqueConstraint(
            "normalization_rule_id",
            "identifier_kind",
            "normalized_value",
            "entity_type_code",
            "entity_scope",
            name="uq_entity_identifiers_strong_identity",
        ),
    )
    op.create_index(
        "ix_entity_identifiers_entity", "entity_identifiers", ["entity_id"], unique=False
    )
    op.create_table(
        "entity_mentions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("extraction_run_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_span_id", sa.Uuid(), nullable=False),
        sa.Column("surface_form", sa.Text(), nullable=False),
        sa.Column(
            "mention_status",
            sa.String(length=20),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["entity_candidates.id"],
            name=op.f("fk_entity_mentions_candidate_id_entity_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunks.id"],
            name=op.f("fk_entity_mentions_chunk_id_chunks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
            name=op.f("fk_entity_mentions_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_span_id"],
            ["evidence_spans.id"],
            name=op.f("fk_entity_mentions_evidence_span_id_evidence_spans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["extraction_run_id"],
            ["extraction_runs.id"],
            name=op.f("fk_entity_mentions_extraction_run_id_extraction_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_mentions")),
        sa.UniqueConstraint("candidate_id", name="uq_entity_mentions_candidate"),
    )
    op.create_index("ix_entity_mentions_chunk", "entity_mentions", ["chunk_id"], unique=False)
    op.create_index("ix_entity_mentions_entity", "entity_mentions", ["entity_id"], unique=False)
    op.create_table(
        "relationship_assertions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("extraction_run_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_span_id", sa.Uuid(), nullable=False),
        sa.Column("subject_entity_id", sa.Uuid(), nullable=False),
        sa.Column("object_entity_id", sa.Uuid(), nullable=False),
        sa.Column("predicate_code", sa.String(length=50), nullable=False),
        sa.Column("assertion_kind", sa.String(length=20), nullable=False),
        sa.Column("review_status", sa.String(length=20), nullable=False),
        sa.Column("network_layer", sa.String(length=30), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'inactive')", name=op.f("ck_relationship_assertions_valid_status")
        ),
        sa.ForeignKeyConstraint(
            ["evidence_span_id"],
            ["evidence_spans.id"],
            name=op.f("fk_relationship_assertions_evidence_span_id_evidence_spans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["extraction_run_id"],
            ["extraction_runs.id"],
            name=op.f("fk_relationship_assertions_extraction_run_id_extraction_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["object_entity_id"],
            ["entities.id"],
            name=op.f("fk_relationship_assertions_object_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_candidate_id"],
            ["relationship_candidates.id"],
            name=op.f("fk_relationship_assertions_source_candidate_id_relationship_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subject_entity_id"],
            ["entities.id"],
            name=op.f("fk_relationship_assertions_subject_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relationship_assertions")),
        sa.UniqueConstraint("source_candidate_id", name="uq_relationship_assertions_candidate"),
    )
    op.create_index(
        "ix_relationship_assertions_object",
        "relationship_assertions",
        ["object_entity_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_relationship_assertions_predicate",
        "relationship_assertions",
        ["predicate_code", "status"],
        unique=False,
    )
    op.create_index(
        "ix_relationship_assertions_subject",
        "relationship_assertions",
        ["subject_entity_id", "status"],
        unique=False,
    )
    op.create_table(
        "resolution_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("extraction_run_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("matched_entity_id", sa.Uuid(), nullable=True),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("method", sa.String(length=50), nullable=False),
        sa.Column("score", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("rule_version", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("decided_by", sa.String(length=100), nullable=False),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('create', 'merge', 'keep_separate', 'defer')",
            name=op.f("ck_resolution_decisions_valid_decision"),
        ),
        sa.CheckConstraint(
            "method IN ('deterministic_new', 'deterministic_strong_identifier', 'human')",
            name=op.f("ck_resolution_decisions_valid_method"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["entity_candidates.id"],
            name=op.f("fk_resolution_decisions_candidate_id_entity_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["extraction_run_id"],
            ["extraction_runs.id"],
            name=op.f("fk_resolution_decisions_extraction_run_id_extraction_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["matched_entity_id"],
            ["entities.id"],
            name=op.f("fk_resolution_decisions_matched_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resolution_decisions")),
        sa.UniqueConstraint("candidate_id", name="uq_resolution_decisions_candidate"),
    )
    op.create_index(
        "ix_resolution_decisions_run", "resolution_decisions", ["extraction_run_id"], unique=False
    )
    op.create_table(
        "resolution_review_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("source_entity_id", sa.Uuid(), nullable=True),
        sa.Column("target_entity_id", sa.Uuid(), nullable=False),
        sa.Column("match_method", sa.String(length=30), nullable=False),
        sa.Column("score", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'rejected', 'deferred')",
            name=op.f("ck_resolution_review_candidates_valid_status"),
        ),
        sa.CheckConstraint(
            "score >= 0 AND score <= 1", name=op.f("ck_resolution_review_candidates_valid_score")
        ),
        sa.ForeignKeyConstraint(
            ["source_candidate_id"],
            ["entity_candidates.id"],
            name=op.f("fk_resolution_review_candidates_source_candidate_id_entity_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_entity_id"],
            ["entities.id"],
            name=op.f("fk_resolution_review_candidates_source_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_entity_id"],
            ["entities.id"],
            name=op.f("fk_resolution_review_candidates_target_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resolution_review_candidates")),
        sa.UniqueConstraint(
            "source_candidate_id",
            "target_entity_id",
            "match_method",
            name="uq_resolution_review_candidate_pair",
        ),
    )
    op.create_index(
        "ix_resolution_review_queue",
        "resolution_review_candidates",
        ["status", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_resolution_review_queue", table_name="resolution_review_candidates")
    op.drop_table("resolution_review_candidates")
    op.drop_index("ix_resolution_decisions_run", table_name="resolution_decisions")
    op.drop_table("resolution_decisions")
    op.drop_index("ix_relationship_assertions_subject", table_name="relationship_assertions")
    op.drop_index("ix_relationship_assertions_predicate", table_name="relationship_assertions")
    op.drop_index("ix_relationship_assertions_object", table_name="relationship_assertions")
    op.drop_table("relationship_assertions")
    op.drop_index("ix_entity_mentions_entity", table_name="entity_mentions")
    op.drop_index("ix_entity_mentions_chunk", table_name="entity_mentions")
    op.drop_table("entity_mentions")
    op.drop_index("ix_entity_identifiers_entity", table_name="entity_identifiers")
    op.drop_table("entity_identifiers")
    op.drop_index("ix_entity_aliases_normalized", table_name="entity_aliases")
    op.drop_table("entity_aliases")
    op.drop_index("ix_entities_type_normalized", table_name="entities")
    op.drop_index("ix_entities_scope_status", table_name="entities")
    op.drop_table("entities")
    op.drop_index("ix_claims_run_status", table_name="claims")
    op.drop_table("claims")
    op.drop_index("ix_neo4j_projection_runs_vault_created", table_name="neo4j_projection_runs")
    op.drop_table("neo4j_projection_runs")
    op.drop_table("identifier_normalization_rules")
    # ### end Alembic commands ###
